### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/Sequence-a-genome#3]
we need to find and add some small fastq file with reads (the best would be to have a subset of our real data)

**Comment by wirawara** [comment]
Sure. Agreed. That's pretty straightforward. As soon as we get things from Vladimir we can make it.

**Comment by KamilSJaron** [comment]
One of technical replicates of one of control samples will be used (it is really small - 50 MB): LM2_L1_R1.fastq
