### ISSUE TITLE
Instalation guide

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/Sequence-a-genome#4]
They need to install some programs:
- R (module add R/3.2.2;)
- kallisto  (module add UHTS/Analysis/kallisto/0.42.4;)

???

**Comment by KamilSJaron** [comment]
From the last year:
• Latest version of Java (https://www.java.com/en/)
• IGV (http://www.broadinstitute.org/igv/)

**Comment by wirawara** [comment]
They will run R on their computers rather on Vital-IT. It's easier, because they need to find their files, rather than rsync things from server to computer.

**Comment by wirawara** [comment]
The packages in R:
- edgeR - https://bioconductor.org/packages/release/bioc/html/edgeR.html
- tximport (only available in April)

**Comment by KamilSJaron** [comment]
Java is trivial on linux and vital-it.

fastqc and kallisto have written manuals.

R packagess are mentioned without specification, how to install them.

Do we need IGV??

**Comment by wirawara** [comment]
Yup.

**Comment by KamilSJaron** [comment]
All done.

The only thing we have to do is to make a revision once the tximport package will be out... THerefore I leave this issue open.

**Comment by KamilSJaron** [comment]
samtools

**Comment by KamilSJaron** [comment]
Installation guide section was erased - they will load every module when they need it. Local installation is not compulsory.
