### ISSUE TITLE
Change of fasta file in se2ex1

### ISSUE THREAD

**Issue by wirawara** [KamilSJaron/Sequence-a-genome#7]
Would you mind changing Amphioxus HOX cluster to our bacterial genome fasta files? They can learn a bit more about bacteria that we are working on.

**Comment by KamilSJaron** [comment]
Yes, it is really good idea. I have just taken the first small fasta I found on the cluster, but taking our genome is way way more intelligent.

**Comment by KamilSJaron** [comment]
Done; it is non standard fasta (it has no newlines in sequence), but I do not care anymore...
